return {
	-- =========================
	-- "ass" substring (avoid blocking: class, pass, etc.)
	-- =========================
	"class",
	"classes",
	"classic",
	"classics",
	"classical",
	"classroom",
	"classrooms",
	"classify",
	"classified",
	"classifier",
	"classifiers",
	"classification",
	"classifications",
	"classifying",
	"classless",
	"classmate",
	"classmates",
	"classwork",
	"pass",
	"passes",
	"passed",
	"passing",
	"passable",
	"passage",
	"passages",
	"passenger",
	"passengers",
	"passive",
	"passively",
	"passivity",
	"passion",
	"passions",
	"passionate",
	"passionately",
	"compass",
	"compasses",
	"password",
	"passwords",
	"bypass",
	"bypasses",
	"bypassed",
	"bypassing",
	"surpass",
	"surpasses",
	"surpassed",
	"surpassing",
	"trespass",
	"trespasses",
	"trespassed",
	"trespassing",
	"embarrass",
	"embarrasses",
	"embarrassed",
	"embarrassing",
	"embarrassment",
	"embarrassments",
	"harass",
	"harasses",
	"harassed",
	"harassing",
	"harassment",
	"harassments",
	"assist",
	"assists",
	"assisted",
	"assisting",
	"assistant",
	"assistants",
	"assistantship",
	"assistance",
	"assistive",
	"assessor",
	"assessors",
	"assess",
	"assesses",
	"assessed",
	"assessing",
	"assessment",
	"assessments",
	"associate",
	"associates",
	"associated",
	"associating",
	"association",
	"associations",
	"associative",
	"assign",
	"assigns",
	"assigned",
	"assigning",
	"assignment",
	"assignments",
	"assignee",
	"assignees",
	"assume",
	"assumes",
	"assumed",
	"assuming",
	"assumption",
	"assumptions",
	"assurance",
	"assurances",
	"assure",
	"assures",
	"assured",
	"assuring",
	"asset",
	"assets",
	"assetting",
	"mass",
	"masses",
	"massive",
	"massively",
	"massiveness",
	"massacre",
	"massacres",
	"massachusetts",
	"glass",
	"glasses",
	"grass",
	"grasses",
	"grassy",
	"brass",
	"brassy",
	"bass",
	"bassline",
	"basslines",
	"bassist",
	"bassists",
	"cassette",
	"cassettes",
	"cassowary",
	"cassowaries",
	"carcass",
	"carcasses",
	"morass",
	"morasses",
	"ambassador",
	"ambassadors",

	-- =========================
	-- "anal" substring (analysis/analog/analytics)
	-- =========================
	"analysis",
	"analyses",
	"analyze",
	"analyzes",
	"analyzed",
	"analyzing",
	"analyzer",
	"analyzers",
	"analyst",
	"analysts",
	"analytics",
	"analytical",
	"analytically",
	"analog",
	"analogs",
	"analogue",
	"analogues",
	"analogic",
	"analogical",
	"analogies",
	"analogy",

	-- =========================
	-- "cum" substring (document/accumulate/circum-)
	-- =========================
	"document",
	"documents",
	"documented",
	"documenting",
	"documentation",
	"documentations",
	"documentary",
	"documentaries",
	"accumulate",
	"accumulates",
	"accumulated",
	"accumulating",
	"accumulation",
	"accumulations",
	"cumulative",
	"cumulatively",
	"circumstance",
	"circumstances",
	"circumstantial",
	"circumstantially",
	"circumvent",
	"circumvents",
	"circumvented",
	"circumventing",
	"circumvention",
	"circumventions",
	"circumference",
	"circumferences",
	"circumnavigate",
	"circumnavigates",
	"circumnavigated",
	"circumnavigating",
	"circumnavigation",
	"circumnavigational",

	-- =========================
	-- "sex" substring (Sussex/Essex/unisex/etc.)
	-- =========================
	"sussex",
	"essex",
	"middlesex",
	"unisex",
	"unisexes",
	"asexual",
	"asexuality",
	"asexually",
	"sexton",
	"sextons",
	"sextant",
	"sextants",

	-- =========================
	-- "rape" substring (grape/scrape/rapeseed)
	-- =========================
	"grape",
	"grapes",
	"grapefruit",
	"scrape",
	"scrapes",
	"scraped",
	"scraping",
	"scrapebook",
	"scrapebooks",
	"rapeseed",
	"rapeseeds",

	-- =========================
	-- "cock" substring (cockpit/cocktail/peacock)
	-- =========================
	"cockpit",
	"cockpits",
	"cocktail",
	"cocktails",
	"cockerel",
	"cockerels",
	"peacock",
	"peacocks",

	-- =========================
	-- "tit" substring (titan/latitude/attitude/etc.)
	-- =========================
	"titan",
	"titans",
	"titanic",
	"titanium",
	"latitude",
	"latitudes",
	"attitude",
	"attitudes",
	"gratitude",
	"multitude",
	"multitudes",
	"fortitude",
	"solicitude",
	"aptitude",
	"altitude",
	"altitudes",
	"magnitude",
	"magnitudes",
	"exactitude",

	-- =========================
	-- "shit" substring (shiitake)
	-- =========================
	"shiitake",
	"shiitakes",

	-- =========================
	-- "dick" substring (dictionary/predict/addiction/indicator/etc.)
	-- =========================
	"dictionary",
	"dictionaries",
	"predict",
	"predicts",
	"predicted",
	"predicting",
	"prediction",
	"predictions",
	"predictable",
	"predictably",
	"predictor",
	"predictors",
	"predictive",
	"unpredictable",
	"unpredictably",
	"addiction",
	"addictions",
	"addictive",
	"addictively",
	"indicator",
	"indicators",
	"indication",
	"indications",
	"indicative",
	"indict",
	"indicts",
	"indicted",
	"indicting",
	"indictment",
	"indictments",
	"edict",
	"edicts",
	"verdict",
	"verdicts",
	"contradict",
	"contradicts",
	"contradicted",
	"contradicting",
	"contradiction",
	"contradictions",
	"contradictory",
	"interdict",
	"interdicts",
	"interdicted",
	"interdicting",

	-- =========================
	-- "porn" substring (porous/porosity/porphyry)
	-- =========================
	"porous",
	"porosity",
	"porosities",
	"porphyry",
	"porphyria",

	-- =========================
	-- "cunt" substring (classic false-positive)
	-- =========================
	"scunthorpe",

	-- =========================
	-- Portuguese: "pau" substring (pause/paused/unpaused, pausa/pausar)
	-- =========================
	"pause",
	"pauses",
	"paused",
	"pausing",
	"unpause",
	"unpauses",
	"unpaused",
	"unpausing",
	"pausa",
	"pausas",
	"pausar",
	"pausado",
	"pausada",
	"pausados",
	"pausadas",
	"pausando",
	"pausou",
	"paul",
	"paula",
	"paulo",
	"pauline",
	"paulista",
	"paulistas",

	-- =========================
	-- "pis" substring (pistol/piston/epistle/piste)
	-- =========================
	"pistol",
	"pistols",
	"piston",
	"pistons",
	"piste",
	"pistes",
	"epistle",
	"epistles",

	-- =========================
	-- "con" substring (config/control/connection/console/construct…)
	-- =========================
	"con",
	"cone",
	"cones",
	"conic",
	"conical",
	"conics",
	"concept",
	"concepts",
	"conceptual",
	"conceptually",
	"concern",
	"concerns",
	"concerned",
	"concerning",
	"concert",
	"concerts",
	"conclude",
	"concludes",
	"concluded",
	"concluding",
	"conclusion",
	"conclusions",
	"conclusive",
	"conclusively",
	"concurrent",
	"concurrently",
	"concurrency",
	"condition",
	"conditions",
	"conditional",
	"conditionally",
	"configure",
	"configures",
	"configured",
	"configuring",
	"config",
	"configs",
	"configuration",
	"configurations",
	"conflict",
	"conflicts",
	"conflicted",
	"conflicting",
	"connect",
	"connects",
	"connected",
	"connecting",
	"connection",
	"connections",
	"connector",
	"connectors",
	"connectivity",
	"console",
	"consoles",
	"consolidate",
	"consolidates",
	"consolidated",
	"consolidating",
	"consolidation",
	"constant",
	"constants",
	"consistency",
	"consistent",
	"consistently",
	"construct",
	"constructs",
	"constructed",
	"constructing",
	"construction",
	"constructions",
	"constructive",
	"constructor",
	"constructors",
	"consume",
	"consumes",
	"consumed",
	"consuming",
	"consumer",
	"consumers",
	"consumption",
	"contain",
	"contains",
	"contained",
	"containing",
	"container",
	"containers",
	"content",
	"contents",
	"context",
	"contexts",
	"control",
	"controls",
	"controlled",
	"controlling",
	"controller",
	"controllers",
	"controversy",
	"convenient",
	"convenience",
	"convention",
	"conventions",
	"convert",
	"converts",
	"converted",
	"converting",
	"conversion",
	"conversions",

	-- =========================
	-- Portuguese/Spanish/French: "cu" substring (common safe words)
	-- =========================
	"culture",
	"cultural",
	"culturally",
	"cultures",
	"curious",
	"curiously",
	"curiosity",
	"current",
	"currently",
	"currency",
	"currencies",
	"curved",
	"curve",
	"curves",
	"curving",
	"cursor",
	"cursors",
	"custom",
	"customs",
	"customer",
	"customers",
	"customize",
	"customized",
	"customization",
	"customizing",
	"custo",
	"custos",
	"custear",
	"custeio",
	"cultura",
	"culturas",
	"culturalmente",
	"curto",
	"curta",
	"curtos",
	"curtas",
	"curtir",
	"curtindo",
	"curtiu",
	"curva",
	"curvas",
	"curvatura",
	"cursar",
	"curso",
	"cursos",
	"curioso",
	"curiosa",
	"curiosos",
	"curiosas",
	"curiosidade",
	"curiosidades",
	"cuidados",
	"cuidado",
	"cuidar",
	"cuidadoso",
	"cuidadosa",
	"cuidando",
	"cuidou",
	"cumulativo",
	"cumulativa",
	"acumular",
	"acumulado",
	"acumulada",
	"acumulados",
	"acumuladas",

	-- =========================
	-- Additional high-frequency tech/game words that often collide with substrings
	-- =========================
	"assetbundle",
	"assetbundles",
	"passcode",
	"passcodes",
	"passphrase",
	"passphrases",
	"overpass",
	"underpass",
	"bypassable",
	"classpath",
	"classpaths",
	"classloader",
	"classloaders",
	"analysisreport",
	"analysistool",
	"documentationpage",
	"documentationpages",
	"connecttimeout",
	"connectiontimeout",
	"reconnect",
	"reconnected",
	"reconnecting",
	"reconnection",
	"controllerinput",
	"controllerinputs",
	"controllerlayout",
	"controllerlayouts",
	"configurationfile",
	"configurationfiles",
	"customizationmenu",
	"customizationmenus",
	"pausedstate",
	"unpausedstate"
}
