return {
	-- "ass" falsos positivos comuns (sem incluir "ass")
    "bass",
	"class",
	"classes",
	"classic",
	"classical",
	"classroom",
	"classrooms",
	"classify",
	"classified",
	"classification",
	"classifications",
	"pass",
	"passes",
	"passed",
	"passing",
	"passive",
	"passively",
	"passion",
	"passionate",
	"password",
	"passwords",
	"compass",
	"compasses",
	"embarrass",
	"embarrassed",
	"embarrassing",
	"embarrassment",
	"embarrassments",
	"assist",
	"assists",
	"assisted",
	"assisting",
	"assistant",
	"assistants",
	"assistance",
	"assistive",
	"associate",
	"associates",
	"associated",
	"associating",
	"association",
	"associations",
	"assign",
	"assigned",
	"assigning",
	"assignment",
	"assignments",
	"assume",
	"assumed",
	"assumes",
	"assuming",
	"assumption",
	"assumptions",
	"grass",
	"grasses",
	"glass",
	"glasses",
	"mass",
	"masses",
	"massive",
	"massively",

	-- "anal" falsos positivos técnicos (sem incluir "anal")
	"analysis",
	"analyses",
	"analyze",
	"analyzed",
	"analyzing",
	"analyst",
	"analysts",
	"analytics",
	"analytical",
	"analog",
	"analogs",
	"analogue",
	"analogues",
	"analogy",
	"analogies",

	-- "cum" falsos positivos comuns (sem incluir "cum")
	"document",
	"documents",
	"documented",
	"documenting",
	"documentation",
	"accumulate",
	"accumulated",
	"accumulates",
	"accumulating",
	"accumulation",
	"accumulations",
	"cumulative",
	"cumulatively",
	"circumstance",
	"circumstances",
	"circumstantial",
	"circumvent",
	"circumvented",
	"circumventing",
	"circumvention",
	"circumference",
	"circumferences",
	"circumnavigate",
	"circumnavigation",

	-- "sex" falsos positivos (sem incluir "sex")
	"sussex",
	"unisex",
	"middlesex",
	"essex",

	-- "rape" falsos positivos (sem incluir "rape")
	"grape",
	"grapes",
	"grapefruit",
	"scrape",
	"scrapes",
	"scraped",
	"scraping",
	"rapeseed",
	"rapeseeds",

	-- "cock" falsos positivos (sem incluir "cock")
	"cockpit",
	"cockpits",
	"cocktail",
	"cocktails",
	"cockerel",
	"cockerels",
	"peacock",
	"peacocks",

	-- "tit" falsos positivos (sem incluir "tit")
	"titan",
	"titans",
	"titanic",
	"titanium",
	"latitude",
	"attitude",
	"gratitude",
	"multitude",

	-- "shit" falsos positivos (sem incluir "shit")
	"shiitake",
	"shiitakes",

	-- casos clássicos de "substring" em topônimos/palavras conhecidas
	"scunthorpe"
}
